xpserver/blueprints/web.py
import itertools
import os
from flask import render_template, redirect, Response
from flask.blueprints import Blueprint
from flask.helpers import url_for
from sqlalchemy import func
from sqlalchemy.sql.expression import literal_column
from ..model import Experiment, Run, Trial, Block, db, TrialMeasureValue, trial_factor_values
from ..model import Measure, FactorValue, Factor
from _utils import inject_model, convert_date
from api.run import generate_run_trials_info

web_blueprint = Blueprint('web', os.path.splitext(__name__)[0])
web_blueprint.url_value_preprocessor(inject_model)


def _get_free_name(name, others, prefix):
    if name in others:
        name = prefix + name
        prop = name
        num = 0
        while prop in others:
            prop = name + '_' + str(num)
            num += 1
        return prop
    return name


@web_blueprint.route('/')
def index():
    return render_template('experiments_list.html',
                           experiments=Experiment.query.all())


@web_blueprint.route('/experiment/<experiment>')
def experiment(experiment):
    run_statuses = (db.session.query(Run,
                                     func.count(Trial.completion_date),
                                     func.count(Trial.number))
                    .outerjoin(Block, Trial)
                    .group_by(Run.id)).all()
    return render_template('experiment.html',
                           run_statuses=run_statuses,
                           experiment=experiment,
                           completed_nb=len(filter(lambda e: e[1] == e[2], run_statuses)),
                           total_nb=len(run_statuses))


@web_blueprint.route('/experiment/<experiment>.csv')
def generate_trial_csv(experiment):
    def generate():
        # Create a big request that selects factors and measures and if they have id
        # conflicts. Returns the ids in alpha order, factors first.
        factor_ids = map(
            lambda x: x[0],
            db.session.query(Factor.id).join(Experiment)
                                       .filter(Factor.experiment == experiment)
                                       .order_by(Factor.id)
        )
        measure_ids = map(
            lambda x: x[0],
            db.session.query(Measure.id).filter_by(trial_level=True)
                                        .filter(Measure.experiment == experiment)
                                        .join(Experiment)
                                        .order_by(Measure.id)
        )

        # Create the orders.
        header_ids = ['experiment_id',
                      'run_id',
                      'block_number',
                      'measured_block_number',
                      'trial_number',
                      'practice',
                      'server_completion_date']

        # Yield the header row.
        yield ', '.join(itertools.chain(
            header_ids,
            (_get_free_name(f, itertools.chain(measure_ids, header_ids), '_factor_')
             for f in factor_ids),
            (_get_free_name(m, itertools.chain(factor_ids, header_ids), '_measure_')
             for m in measure_ids)
        )) + '\n'

        # From 3 records, yield each cell in the right order.
        def generate_cells(trial, factors, measures):
            for h in header_ids:
                yield trial.get(h, '')
            for f in factor_ids:
                yield factors.get(f, '')
            for m in measure_ids:
                yield measures.get(m, '')

        # Request factor values and measure values.
        factor_values = db.session.query(Factor.id.label('id'),
                                         FactorValue.id.label('value'),
                                         Trial.number,
                                         Trial.completion_date,
                                         Block.number,
                                         Block.practice,
                                         Run.id,
                                         literal_column('"factors"')) \
            .join(Factor, FactorValue.factor) \
            .join(trial_factor_values, Trial, Block, Run)
        measure_values = db.session.query(Measure.id.label('id'),
                                          TrialMeasureValue.value.label('value'),
                                          Trial.number,
                                          Trial.completion_date,
                                          Block.number,
                                          Block.practice,
                                          Run.id,
                                          literal_column('"measures"')) \
            .join(TrialMeasureValue, Trial, Block, Run)
        values = measure_values.union_all(factor_values) \
            .order_by(Run.id, Block.number, Trial.number)

        current_record = None
        current_measured_block_num = None
        current_trial_number = None
        current_block_number = None
        current_run_id = None
        for [
            value_id,
            value,
            trial_number,
            completion_date,
            block_number,
            practice,
            run_id,
            value_group
        ] in values:
            # Case we changed trial
            if current_record is not None and not (trial_number == current_trial_number and
                                                   block_number == current_block_number and
                                                   current_run_id == run_id):
                # Yield the current record.
                yield ','.join(generate_cells(**current_record)) + '\n'
                # Reset the values.
                current_record = None
            if not current_record:
                current_trial_number = trial_number
                current_measured_block_num = (
                    0 if not current_measured_block_num and not practice
                    else current_measured_block_num if practice
                    else current_measured_block_num + 1
                )
                current_block_number = block_number
                current_run_id = run_id
                # print(type(completion_date))
                current_record = {
                    'trial': {
                        'server_completion_date': (
                            str(convert_date(completion_date)) if completion_date
                            else ''
                        ),
                        'experiment_id': experiment.id,
                        'run_id': run_id,
                        'block_number': str(block_number),
                        'measured_block_number': (
                            '' if practice else str(current_measured_block_num)
                        ),
                        'trial_number': str(trial_number),
                        'practice': str(practice)
                    }, 'factors': {}, 'measures': {}
                }
            current_record[value_group][value_id] = value
        # Yield the last record
        yield ','.join(generate_cells(**current_record)) + '\n'

    return Response(generate(), mimetype='text/csv')


@web_blueprint.route('/run/<experiment>/<run>/unlock')
def unlock_run(experiment, run):
    run.token = None
    db.session.commit()
    return redirect(url_for('.experiment', experiment=experiment.id))


@web_blueprint.route('/run/<experiment>/<run>/results')
def run_results(experiment, run):
    factors = sorted(experiment.factors, key=lambda x: x.id)
    trial_measures = sorted((measure
                             for measure in experiment.measures.itervalues()
                             if measure.trial_level),
                            key=lambda x: x.id)
    factor_values_names = dict(db.session.query(FactorValue.id, FactorValue.name)
                               .join(FactorValue.factor)
                               .filter(Factor.experiment == experiment)
                               .filter(FactorValue.name.isnot(None)))
    return render_template('results_static.html',
                           trials=list(generate_run_trials_info(run, completed_only=True)),
                           trial_measures=trial_measures,
                           factor_values_names=factor_values_names,
                           factors=factors,
                           run=run,
                           experiment=experiment)


@web_blueprint.route('/trial/<experiment>/<run>/<int:block>/<int:trial>/events')
def events(experiment, run, block, trial):
    event_measures = sorted((measure for measure
                            in experiment.measures.itervalues()
                            if measure.event_level),
                            key=lambda x: x.id)
    return render_template('events.html',
                           trial=trial,
                           block=block,
                           event_measures=event_measures,
                           run=run,
                           experiment=experiment)

xpserver/templates/events.html
<!DOCTYPE html>

<html>

<head>
    {% block head %}
        <meta http-equiv="content-type" content="text/html; charset=utf-8">

        <title>{% block title %}Events: {{ run.id }} ({{ experiment.name }}){% endblock %}</title>


        {% block styles %}
            <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/results.css') }}">
        {% endblock %}

        {% block scripts %}{% endblock %}

    {% endblock head %}
</head>

<body>
{% block body %}

    <h1 id='title'>Events of trial {{ trial.number }} in block {{ block.number }}</h1>

    <div id="container">
        {% block content %}{% strip %}
            <table class="gridtable" id='events' data-run='{{ run.id }}' data-experiment='{{ experiment.id }}' data-block='{{ block.number }}' data-trial='{{ trial.number }}'>
                <thead>
                {%- block table_head -%}
                    {% set cycle = cycler('odd', 'even') %}
                    <tr id='events-header' class='table-header'>

                        <th class='column-event-number {{ " " + cycle.next() }}' data-column-type='info' data-info='event_number'>
                            Event number
                        </th>

                        {% for measure in event_measures %}
                            <th class='column-{{ measure.id }}-measure {{ ' ' + cycle.next() }}'
                                data-column-type='measure' data-measure='{{ measure.id }}'
                                title='measure id: {{ ' '+ measure.id }}'>
                                {{- measure.name or measure.id -}}
                            </th>
                        {% endfor %}
                    </tr>
                {% endblock %}
                </thead>
                <tbody>{% block table_body %}

                    {% for event in trial.events %}
                        {% set cycle = cycler('odd', 'even') %}
                        <tr id="event-{{ event.number }}"
                            data-event-number='{{ event.number }}'>

                            <th class="column-event-number {{ ' ' + cycle.next() }}" data-column-type='info'
                                data-info="event-number">
                                {{ event.number }}
                            </th>


                            {% for measure in event_measures %}
                                <td class="column-{{ measure.id }}-measure {{ ' '+cycle.next() }}" data-column-type='measure'
                                    data-measure='{{ measure.id }}'>
                                    {% if measure.id in event.measure_values %}
                                        {{ event.measure_values[measure.id].value }}
                                    {% endif %}
                                </td>
                            {% endfor %}
                        </tr>
                    {% endfor %}


                {% endblock %}</tbody>
            </table>
        {% endstrip %}{% endblock %}
    </div>

{% endblock body %}
</body>

</html>

xpserver/templates/experiment.html
<!DOCTYPE html>

<html>

<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <title>Experiment {{ experiment.name or experiment.id }}'s Status</title>

    {% block styles %}
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/xp_status.css') }}">
    {% endblock %}

</head>

<body>

    <h1>Experiment {{ experiment.name or experiment.id }}'s Status</h1>

    <div id="summary">
        Run completed: {{ completed_nb }}/{{ total_nb }}
    </div>

    <table id="table-status">
        <colgroup>
            <col class="col-run-info" span="2">
            <col class="col-run-unlock">
        </colgroup>
        {% set cycle = cycler('odd', 'even') %}
        {% for run_entry in run_statuses %}
            {% set run_status = 'completed' if run_entry[1] == run_entry[2] else ('started' if run_entry[1] > 0 else 'unstarted') %}
            {% set run = run_entry[0] %}
            {% set run_ref = '/run/' + experiment.id + '/' + run.id + '/results' %}
            <tr class="run-row run-{{ run_status }} {{ cycle.next() }}" run-id="{{ run.id }}">
                <th class="run-id"><a class="run-link" href="{{run_ref}}"><span class="cell-content">{{ run.id }}</span></a></th>
                <td class="run-status"><a class="run-link" href="{{run_ref}}"><span class="cell-content">{{ run_status }}</span></a></td>
                <td class="run-lock">
                  {% if run.locked %}
                    <span class="cell-content"><a
                      href="{{url_for('web.unlock_run', experiment=experiment.id, run=run.id)}}"
                      title="Unlock run {{ run.id }}"
                      onclick="return confirm('Unlock run {{ run.id }}?\nThis might interrupt a participant.')"
                      class="run-lock-link"
                    ><img class="unlock-icon" src="{{ url_for('static', filename='images/padlock-unlock.svg') }}"></img><img class="lock-icon" src="{{ url_for('static', filename='images/padlock.svg') }}"></img></a></span>
                  {% endif %}
                </td>
            </tr>
        {% endfor %}
    </table>
    <div id="downloads">
      <a class="download-link download-results" href="{{url_for('web.generate_trial_csv', experiment=experiment.id)}}" download>Download results</a>
    </div>
</body>

xpserver/templates/experiments_list.html
<!DOCTYPE html>

<html>

<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <title>Experiments list</title>

    {% block styles %}
    {% endblock %}

</head>

<body>

<h1>Experiments list</h1>


<ul id="xp-list">
    {% for xp in experiments %}
        <li><a href="{{ url_for('web.experiment', experiment=xp.id)}}">{{ xp.name or xp.id }}</a></li>
    {% endfor %}
</ul>
</body>

xpserver/templates/results.html
<!DOCTYPE html>

<html>

<head>
    {% block head %}
        <meta http-equiv="content-type" content="text/html; charset=utf-8">

        <title>{% block title %}Trial results: {{ run.id }} ({{ experiment.name or experiment.id }}){% endblock %}</title>


        {% block styles %}
            <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/results.css') }}">
        {% endblock %}

        {% block scripts %}{% endblock %}

    {% endblock head %}
</head>

<body>
{% block body %}

    <h1 id='title'>Trial results of run {{ run.id }} of experiment '{{  experiment.name or experiment.id }}'</h1>

    <div id="container">
        {% block content %}{% strip %}
            <table class="gridtable" id='trial-results' data-run='{{ run.id }}' data-experiment='{{ experiment.id }}'>
                <thead>
                {%- block table_head -%}
                    {% set cycle = cycler('odd', 'even') %}
                    <tr id='trial-results-header' class='table-header'>
                        <th class='column-block-num {{ ' ' + cycle.next() }}' data-column-type='info' data-info="block_number">
                            Block number
                        </th>
                        <th class='column-trial-num {{ ' ' + cycle.next() }}' data-column-type='info' data-info="trial_number">
                            Trial number
                        </th>
                        {% for factor in factors %}
                            <th title='factor id: {{ ' ' + factor.id }}'
                                class='column-{{ factor.id }}-factor {{ ' ' + cycle.next() }}'
                                data-column-type='factor' data-factor='{{ factor.id }}'>
                                  {{- factor.name or factor.id-}}
                            </th>
                        {% endfor %}

                        {% for measure in trial_measures %}
                            <th class='column-{{ measure.id }}-measure {{ ' ' + cycle.next() }}'
                                data-column-type='measure' data-measure='{{ measure.id }}'
                                title='measure id: {{ ' '+ measure.id }}'>
                                  {{- measure.name or measure.id -}}
                            </th>
                        {% endfor %}
                    </tr>
                {% endblock %}
                </thead>
                <tbody>{% block table_body %}{% endblock %}</tbody>
            </table>
        {% endstrip %}{% endblock %}
    </div>

{% endblock body %}
</body>

</html>

xpserver/templates/results_static.html
{% extends "results.html" %}

{% block table_body %}{% strip %}
    {% for trial in trials %}
        {% set cycle = cycler('odd', 'even') %}
        <tr
            id="trial-results-{{ trial.blockNumber }}-{{ trial.number }}"
            data-trial-number='{{ trial.number }}'
            data-block-number='{{ trial.blockNumber }}'
            onclick="window.location='/trial/{{ experiment.id }}/{{ run.id }}/{{ trial.blockNumber }}/{{ trial.number }}/events';"
        >
            <th class="column-block-num {{ ' ' + cycle.next() }}" data-column-type='info' data-info="block_number">
                {{ trial.measuredBlockNumber }}
            </th>
            <th class="column-trial-num {{ ' ' +cycle.next() }}" data-column-type='info' data-info="trial_number">
                {{ trial.number }}
            </th>

            {%- for factor in factors -%}
                <td class="column-{{ factor.id }}-factor {{ ' ' +cycle.next() }}" data-column-type='factor'
                    data-factor='{{ factor.id }}'>
                    {% set value_id = trial.factorValues[factor.id] %}
                    {%- if value_id -%}
                        {{ factor_values_names[value_id] or value_id }}
                    {% endif %}
                </td>
            {%- endfor -%}

            {% for measure in trial_measures %}
                <td class="column-{{ measure.id }}-measure {{ ' '+cycle.next() }}" data-column-type='measure'
                    data-measure='{{ measure.id }}'>
                    {% if measure.id in trial.measures %}
                        {{ trial.measures[measure.id] }}
                    {% endif %}
                </td>
            {% endfor %}
        </tr>
    {% endfor %}
{% endstrip %}{% endblock table_body %}